//
//  SearchModels.swift
//  iMusic
//
//  Created by Max on 25.01.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Search
{
    // MARK: Use cases
    
    enum Something
    {
        struct Request
        {
            let searchTerm: String
        }
        struct Response
        {
            let searchResponse: SearchResponse?
        }
        struct ViewModel
        {
            let searchViewModel: SearchViewModel
        }
    }
}


struct SearchViewModel {
    struct Cell {
        var iconUrlString: String
        var trackName: String
        var collectionName: String
        var artistName: String
    }
    
    var cells: [Cell]
}
