//
//  SearchViewController.swift
//  iMusic
//
//  Created by Max on 25.01.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchDisplayLogic: AnyObject
{
    func displaySomething(viewModel: Search.Something.ViewModel)
    func startLoadingAnimation()
}

class SearchViewController: UIViewController, SearchDisplayLogic
{
    var interactor: SearchBusinessLogic?
    var router: (NSObjectProtocol & SearchRoutingLogic & SearchDataPassing)?
    
    
    @IBOutlet weak var table: UITableView!
    
    let searchController = UISearchController(searchResultsController: nil)
    private var searchViewModel = SearchViewModel.init(cells: [])
    private var timer: Timer?
    
    private lazy var footerView = FooterView()
    
    // MARK: Setup
    
    private func setup()
    {
        let viewController = self
        let interactor = SearchInteractor()
        let presenter = SearchPresenter()
        let router = SearchRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?)
    {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad()
    {
        super.viewDidLoad()
        setup()
        //doSomething()
        setupSearchBar()
        setupTableView()
    }
    
    private func setupSearchBar() {
        navigationItem.searchController = searchController
        navigationItem.hidesSearchBarWhenScrolling = false
        searchController.searchBar.delegate = self
    }
    
    private func setupTableView() {
        table.register(UITableViewCell.self, forCellReuseIdentifier: "cellId")
        
        let nib = UINib(nibName: "TrackCell", bundle: nil)
        table.register(nib, forCellReuseIdentifier: TrackCell.reuseId)
        table.tableFooterView = footerView
    }
    
    // MARK: Do something
    
    //@IBOutlet weak var nameTextField: UITextField!
    
//    func doSomething()
//    {
//        let request = Search.Something.Request()
//        interactor?.doSomething(request: request)
//    }
    
    func displaySomething(viewModel: Search.Something.ViewModel)
    {
        print("ViewModel -----------")
        
        self.searchViewModel = viewModel.searchViewModel
        table.reloadData()
        footerView.hideLoader()
        
        //nameTextField.text = viewModel.name
    }
    
    func startLoadingAnimation() {
        footerView.showLoader()
    }
}

// MARK: - UITableViewDelegate, UITableViewDataSource

extension SearchViewController: UITableViewDelegate, UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return searchViewModel.cells.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = table.dequeueReusableCell(withIdentifier: TrackCell.reuseId, for: indexPath) as! TrackCell
        
        let cellViewModel = searchViewModel.cells[indexPath.row]
        
        cell.trackImageView.backgroundColor = .red
        cell.trackImageView.image = UIImage(named: "Image")
        
        cell.set(viewModel: cellViewModel)
        
        return cell
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        let cellViewModel = searchViewModel.cells[indexPath.row]
        print("indexPath: \(indexPath.row)")
        
        let window = UIApplication.shared.windows.filter {$0.isKeyWindow}.first
        let trackDetailsView: TrackDetailView = TrackDetailView.loadFromNib()
        trackDetailsView.delegate = self
        trackDetailsView.set(viewModel: cellViewModel)
        window?.addSubview(trackDetailsView)
        
    }
    
    func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return 84
    }
    
    func tableView(_ tableView: UITableView, viewForHeaderInSection section: Int) -> UIView? {
        let label = UILabel()
        label.text = "Please enter search text above..."
        label.textAlignment = .center
        label.font = UIFont.systemFont(ofSize: 18, weight: .bold)
        return label
    }

    func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
        return searchViewModel.cells.count > 0 ? 0 : 250
    }
    
}

// MARK: - UISearchBarDelegate

extension SearchViewController: UISearchBarDelegate {
    
    func searchBar(_ searchBar: UISearchBar, textDidChange searchText: String) {
        
        print(searchText)
        
        timer?.invalidate()
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: false, block: { _ in
            let request = Search.Something.Request(searchTerm: searchText)
            self.interactor?.doSomething(request: request)
        })
        
        
    }
}

extension SearchViewController: TrackMovingDelegate {
    
    private func getTrack(isForward: Bool) -> SearchViewModel.Cell? {
        guard let indexPath = table.indexPathForSelectedRow else { return nil }
        table.deselectRow(at: indexPath, animated: true)
        var nextIdexPath: IndexPath!
        if isForward {
            nextIdexPath = IndexPath(row: indexPath.row + 1, section: indexPath.section)
            if nextIdexPath.row == searchViewModel.cells.count {
                nextIdexPath.row = 0
            }
        } else {
            nextIdexPath = IndexPath(row: indexPath.row - 1, section: indexPath.section)
            if nextIdexPath.row == -1 {
                nextIdexPath.row = searchViewModel.cells.count - 1
            }
        }
        
        table.selectRow(at: nextIdexPath, animated: true, scrollPosition: .none)
        let cellViewModel = searchViewModel.cells[nextIdexPath.row]
        return cellViewModel
    }
    
    
    
    func moveBackForPreviousTrack() -> SearchViewModel.Cell? {
        print("Back---------->")
        return getTrack(isForward: false)
    }
    
    func moveForwardForPreviousTrack() -> SearchViewModel.Cell? {
        print("Forward----------->")
        return getTrack(isForward: true)
    }
    
    
}
