//
//  SearchPresenter.swift
//  iMusic
//
//  Created by Max on 25.01.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SearchPresentationLogic
{
    func presentSomething(response: Search.Something.Response)
}

class SearchPresenter: SearchPresentationLogic
{
    weak var viewController: SearchDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: Search.Something.Response) {
        print("Presenter ----------")
        
        let cells = response.searchResponse?.results.map({ track in
            cellViewModel(from: track)
        }) ?? []
        
        let searchViewModel = SearchViewModel(cells: cells)
        let viewModel = Search.Something.ViewModel.init(searchViewModel: searchViewModel)
        viewController?.displaySomething(viewModel: viewModel)
        
        viewController?.startLoadingAnimation()
    }
    
    private func cellViewModel(from track: Track) -> SearchViewModel.Cell {
        
        return SearchViewModel.Cell.init(iconUrlString: track.artworkUrl100 ?? "",
                                         trackName: track.trackName ?? "",
                                         collectionName: track.collectionName ?? "",
                                         artistName: track.artistName,
                                         previewUrl: track.previewUrl)
    }
}
