//
//  SearchWorker.swift
//  iMusic
//
//  Created by Max on 25.01.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class SearchWorker
{
  func doSomeWork()
  {
  }
}
